# Generated by Django 3.1.7 on 2021-03-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_eventregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='event_name',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
